version: "3.8"
services:
  mysql-database:
    build: ./mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: itesm
      MYSQL_DATABASE: itesm502
    ports:
      - "3306:3306"
    restart: always
  class:
    depends_on:
      - mysql-database
    build: ./class
    environment:
      MYSQL_DATABASE: itesm502
      MYSQL_USER: root
      MYSQL_PASSWORD: itesm
      MYSQL_HOST: mysql-database
    ports:
      - "3000:3000"
    restart: on-failure
