version: "3.8"
services:
  mysql-database:
    build: ./mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: D3xJxrvalzdUJ5Jbn%lYSU
      MYSQL_DATABASE: itesm502
    restart: always
  web-nodejs:
    build: ./class
    environment:
      MYSQL_DATABASE: itesm502
      MYSQL_USER: root
      MYSQL_PASSWORD: D3xJxrvalzdUJ5Jbn%lYSU
      MYSQL_HOST: localhost
    ports:
      - "3000:3000"
    depends_on:
      - mysql-database
    restart: on-failure
